import pandas as pd

configfile: "config/config.yaml"

# Read in sample csv and extract the sample names and paths
sample_df = pd.read_csv(config["samples_csv"])
sample_names = list(sample_df["samplename"])
sample_dict_paths = dict(zip(sample_df["samplename"], sample_df["samplepath"]))

# Input function to return the corresponding sample path given a sample name
def get_sample_path(wildcards):
    return sample_dict_paths[wildcards.sample]

rule all:
    input:
        expand("results/{sample}/{sample}.stats.txt", sample=sample_names),
        expand("results/{sample}/{sample}.scevcf.tsv", sample=sample_names)

rule gvcftovcf:
    input:
        gvcf=get_sample_path
    conda:
        "envs/bcftools.yaml"
    output:
        vcf="tmp/{sample}/{sample}.vcf.gz"
    shell:
        """
        bcftools convert --gvcf2vcf \
        --fasta-ref {config[reference_genome]} \
        -Ov {input.gvcf} \
        | awk 'BEGIN {{OFS="\t"}} /^#/ {{print; next}} {{$4 = toupper($4); $5 = toupper($5); print}}' \
        | bcftools view -AA -Oz -o {output.vcf} -
        """

rule bialsnps:
    input:
        vcf="tmp/{sample}/{sample}.vcf.gz"
    conda:
        "envs/bcftools.yaml"
    output:
        snps_vcf="tmp/{sample}/{sample}.bial.snps.vcf.gz"
    shell:
        """
        bcftools view -f PASS,. -m2 -M2 -v snps  -i "FORMAT/AD!='.'" -Oz -o {output.snps_vcf} {input.vcf}
        tabix -p vcf {output.snps_vcf}
        """

rule aftag:
    input:
        snps_vcf="tmp/{sample}/{sample}.bial.snps.vcf.gz"
    conda:
        "envs/bcftools.yaml"
    output:
        af_vcf="tmp/{sample}/{sample}.bial.snps.AF.vcf.gz"
    shell:
        """
        bcftools annotate -a {config[reference_panel]} \
        -c INFO/AF -Oz -o {output.af_vcf} \
        {input.snps_vcf}
        """

rule sceVCF:
    input:
        af_vcf="tmp/{sample}/{sample}.bial.snps.AF.vcf.gz"
    output:
        scevcf_tsv="results/{sample}/{sample}.scevcf.tsv"
    shell:
        """
        bin/sceVCF -o {output.scevcf_tsv} {input.af_vcf}
        """

rule bcfstats:
    input: 
        vcf="tmp/{sample}/{sample}.vcf.gz"
    conda: 
        "envs/bcftools.yaml"
    threads: 1
    output:
        stats="results/{sample}/{sample}.stats.txt"
    shell:
        """
        bcftools stats --threads {threads} -s - {input.vcf} > {output.stats}
        """

rule gvcfcsv:
    input:
        scevcf_tsv="results/{sample}/{sample}.scevcf.tsv"
        stats="results/{sample}/{sample}.stats.txt"
    output:
        gvcf_csv="results/{sample}/{sample}.contam"
    run:
        warnings = []
        # Check the indels and Ts/Tv ratio
        with open(input.stats, "r") as stats:
            for line_num, line in enumerate(stats, start=1):
                if line_num == 12:
                    content = line.split("\t") 
                    indels = int(content[3])
                    if indels < config["min_indels"]:
                        warnings.append("LOW INDELS")
                    else if indels > config["max_indels"]:
                        warnings.append("HIGH INDELS")
                elif linenum == 36:
                    content = line.split("\t")
                    tstv = float(content[4])
                    if tstv < config["min_tstv"]:
                        warnings.append("LOW TS/TV")
                    elif tstv > config["max_tstv"]:
                        warnings.append("HIGH TS/TV")
        # Check the CHARR and INCONSISTENT_AB_HET_RATE
        with open(input.scevcf_tsv, "r") as scevcf_tsv:
            lines = scevcf_tsv.readlines()
            content = lines[3].split('\t')
            charr = float(content[9])
            inconsistent_ab_het_rate = float(content[12])
            if charr >= config["charr"]:
                warnings.append("CHARR CONTAMINATION")
            if inconsistent_ab_het_rate >= config[inconsistent_ab_het_rate]:
                warnings.append("INCONSISTENT_AB_HET_RATE CONTAMINATION")
        # Append the warnings together to form a label
        label = "/".join(warnings)
        # Create a dataframe containing the gvcf data
        gvcf_data = {
            "Sample": [wildcards.sample],
            "Warnings": [label]
        }
        gvcf_df = pd.DataFrame(bam_data)
        # Write the dataframe to a csv file
        gvcf_df.to_csv(output.bam_csv, index=False)

# Aggregate all the indivdual csv's to one
rule aggcsv:
    input:
        expand("results/{sample}/{sample}.csv", sample=sample_names)
    output:
        contam_csv=config["contam_csv"]
    run:
        # Read in every individual csv
        sample_dfs = [pd.read_csv(file) for file in input]
        # Stack the csv's together to create a new csv
        concat_df = pd.concat(sample_dfs, ignore_index=True)
        concat_df = concat_df[concat_df["Warnings"] != ""]
        concat_df.to_csv(output.contam_csv, index=False)