# Csv containing samplename, breed, samplepath
samples_csv:  "config/samples.csv"

# Output csv detailing contaminated samples
contam_csv: "results/contam.csv"

# Output csv detailing PC coordinates of samples
pc_csv: "results/pc.csv"

# Output html file containing PC plot
pc_plot: "results/pcplot.html"

# Resource files from verifybamid
resource_files: "data/verifybamid/resource_files/dog_wgs.n3973.UU_Cfam_GSD_1.0_ROSY.20251223.snps.phased.filter.prune.vcf.gz"

# Reference genome for canine
reference_genome: "data/reference_genomes/UU_Cfam_GSD_1.0_ROSY/UU_Cfam_GSD_1.0_ROSY.fa.gz"

# Minimum threshold for percentage of reads aligned
percent_aligned: 90

# Minimum threshold for mean coverage of genome
mean_coverage: 20

# Freemix cutoff score
freemix: 0.10